# Generated by Django 5.1.4 on 2024-12-05 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='mame',
            new_name='name',
        ),
    ]
